config/routes.rb
MaileeExample::Application.routes.draw do |map|
  resources :mailee_messages do
    member do
      post :ready
      post :test
    end
  end

  resources :mailee_lists

  resources :mailee_templates

  resources :mailee_contacts

  resources :clients
  root :to => "clients#index"
end

app/controllers/mailee_lists_controller.rb
class MaileeListsController < ApplicationController
  # GET /mailee_lists
  # GET /mailee_lists.xml
  def index
    @mailee_lists = Mailee::List.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @mailee_lists }
    end
  end

  # GET /mailee_lists/1
  # GET /mailee_lists/1.xml
  def show
    @mailee_list = Mailee::List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @mailee_list }
    end
  end

  # GET /mailee_lists/new
  # GET /mailee_lists/new.xml
  def new

    @mailee_list = Mailee::List.new :name => '', :active => '', :company => '', :description => '', :address => '', :phone => '', :site => ''

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @mailee_list }
    end
  end

  # GET /mailee_lists/1/edit
  def edit
    @mailee_list = Mailee::List.find(params[:id])
  end

  # POST /mailee_lists
  # POST /mailee_lists.xml
  def create
    @mailee_list = Mailee::List.new(params[:mailee_list])

    respond_to do |format|
      if @mailee_list.save
        format.html { redirect_to(@mailee_list, :notice => 'Mailee list was successfully created.') }
        format.xml  { render :xml => @mailee_list, :status => :created, :location => @mailee_list }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @mailee_list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /mailee_lists/1
  # PUT /mailee_lists/1.xml
  def update
    @mailee_list = Mailee::List.find(params[:id])

    respond_to do |format|
      if @mailee_list.update_attributes(params[:mailee_list])
        format.html { redirect_to(@mailee_list, :notice => 'Mailee list was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @mailee_list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /mailee_lists/1
  # DELETE /mailee_lists/1.xml
  def destroy
    @mailee_list = Mailee::List.find(params[:id])
    @mailee_list.destroy

    respond_to do |format|
      format.html { redirect_to(mailee_lists_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/mailee_lists_helper.rb
module MaileeListsHelper
end

app/views/mailee_lists/_form.html.erb
<%= form_for(@mailee_list) do |f| %>
  <% if @mailee_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mailee_list.errors.count, "error") %> prohibited this mailee_list from being saved:</h2>

      <ul>
      <% @mailee_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% for field in [:name, :company, :description, :address, :phone, :site] %>
      <%= f.label field %><br />
      <%= f.text_field field %>
      <br />
    <% end %>
  </div>

 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mailee_lists/edit.html.erb
<h1>Editing mailee_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @mailee_list %> |
<%= link_to 'Back', mailee_lists_path %>

app/views/mailee_lists/index.html.erb
<h1>Listing mailee_lists</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mailee_lists.each do |mailee_list| %>
  <tr>
    <td><%= mailee_list.name %></td>
    <td><%= link_to 'Show', mailee_list %></td>
    <td><%= link_to 'Edit', edit_mailee_list_path(mailee_list) %></td>
    <td><%= link_to 'Destroy', mailee_list, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mailee list', new_mailee_list_path %>

app/views/mailee_lists/new.html.erb
<h1>New mailee_list</h1>

<%= render 'form' %>

<%= link_to 'Back', mailee_lists_path %>

app/views/mailee_lists/show.html.erb
<p id="notice"><%= notice %></p>

<% for field in [:name, :company, :description, :address, :phone, :site] %>
<p>
  <b><%= field %>:</b>
  <%= @mailee_list.send(field) %>
</p>
<% end %>

<%= link_to 'Edit', edit_mailee_list_path(@mailee_list) %> |
<%= link_to 'Back', mailee_lists_path %>