config/routes.rb
MaileeExample::Application.routes.draw do |map|
  resources :mailee_messages do
    member do
      post :ready
      post :test
    end
  end

  resources :mailee_lists

  resources :mailee_templates

  resources :mailee_contacts

  resources :clients
  root :to => "clients#index"
end

app/controllers/mailee_templates_controller.rb
class MaileeTemplatesController < ApplicationController
  # GET /mailee_templates
  # GET /mailee_templates.xml
  def index
    @mailee_templates = Mailee::Template.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @mailee_templates }
    end
  end

  # GET /mailee_templates/1
  # GET /mailee_templates/1.xml
  def show
    @mailee_template = Mailee::Template.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @mailee_template }
    end
  end

  # GET /mailee_templates/new
  # GET /mailee_templates/new.xml
  def new
    @mailee_template = Mailee::Template.new(:title => '', :html => '')

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @mailee_template }
    end
  end

  # GET /mailee_templates/1/edit
  def edit
    @mailee_template = Mailee::Template.find(params[:id])
  end

  # POST /mailee_templates
  # POST /mailee_templates.xml
  def create
    @mailee_template = Mailee::Template.new(params[:mailee_template])

    respond_to do |format|
      if @mailee_template.save
        format.html { redirect_to(@mailee_template, :notice => 'Mailee template was successfully created.') }
        format.xml  { render :xml => @mailee_template, :status => :created, :location => @mailee_template }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @mailee_template.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /mailee_templates/1
  # PUT /mailee_templates/1.xml
  def update
    @mailee_template = Mailee::Template.find(params[:id])

    respond_to do |format|
      if @mailee_template.update_attributes(params[:mailee_template])
        format.html { redirect_to(@mailee_template, :notice => 'Mailee template was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @mailee_template.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /mailee_templates/1
  # DELETE /mailee_templates/1.xml
  def destroy
    @mailee_template = Mailee::Template.find(params[:id])
    @mailee_template.destroy

    respond_to do |format|
      format.html { redirect_to(mailee_templates_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/mailee_templates_helper.rb
module MaileeTemplatesHelper
end

app/views/mailee_templates/_form.html.erb
<%= form_for(@mailee_template) do |f| %>
  <% if @mailee_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mailee_template.errors.count, "error") %> prohibited this mailee_template from being saved:</h2>

      <ul>
      <% @mailee_template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :html %><br />
    <%= f.text_area :html %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mailee_templates/edit.html.erb
<h1>Editing mailee_template</h1>

<%= render 'form' %>

<%= link_to 'Show', @mailee_template %> |
<%= link_to 'Back', mailee_templates_path %>

app/views/mailee_templates/index.html.erb
<h1>Listing mailee_templates</h1>

<table>
  <tr>
    <th>Thumb</th>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mailee_templates.each do |mailee_template| %>
  <tr>
    <td><%= image_tag mailee_template.thumb %></td>
    <td><%= mailee_template.title %></td>
    <td><%= link_to 'Show', mailee_template %></td>
    <td><%= link_to 'Edit', edit_mailee_template_path(mailee_template) %></td>
    <td><%= link_to 'Destroy', mailee_template, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mailee template', new_mailee_template_path %>

app/views/mailee_templates/new.html.erb
<h1>New mailee_template</h1>

<%= render 'form' %>

<%= link_to 'Back', mailee_templates_path %>

app/views/mailee_templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @mailee_template.title %>
</p>

<%= link_to 'Edit', edit_mailee_template_path(@mailee_template) %> |
<%= link_to 'Back', mailee_templates_path %>