config/routes.rb
MaileeExample::Application.routes.draw do |map|
  resources :mailee_messages do
    member do
      post :ready
      post :test
    end
  end

  resources :mailee_lists

  resources :mailee_templates

  resources :mailee_contacts

  resources :clients
  root :to => "clients#index"
end

app/models/mailee_message.rb
class MaileeMessage < ActiveRecord::Base
end

app/controllers/mailee_messages_controller.rb
class MaileeMessagesController < ApplicationController
  # GET /mailee_messages
  # GET /mailee_messages.xml
  def index
    @mailee_messages = Mailee::Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @mailee_messages }
    end
  end

  # GET /mailee_messages/1
  # GET /mailee_messages/1.xml
  def show
    @mailee_message = Mailee::Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @mailee_message }
    end
  end

  # GET /mailee_messages/new
  # GET /mailee_messages/new.xml
  def new
    @mailee_message = Mailee::Message.new(:newsletter_id => '', :template_id => '', :list_id => '', :contacts => '', :segment_id => '', :title => '', :subject => '', :from_name => '', :from_email => '', :reply_email => '', :html => '', :analytics => true)

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @mailee_message }
    end
  end

  # GET /mailee_messages/1/edit
  def edit
    @mailee_message = Mailee::Message.find(params[:id])
  end

  # POST /mailee_messages
  # POST /mailee_messages.xml
  def ready
    @mailee_message = Mailee::Message.find(params[:id])
    @mailee_message.ready
    redirect_to @mailee_message
  end
  def create
#    raise params[:mailee_message].inspect
    params[:mailee_message][:content_from] ||= 2 if params[:mailee_message][:html] != ''
    params[:mailee_message][:content_from] ||= 1 if params[:mailee_message][:template_id] != ''

    params[:mailee_message].delete(:contacts) if params[:mailee_message][:contacts] == ''
    
#    raise params[:mailee_message].inspect
    
    @mailee_message = Mailee::Message.new(params[:mailee_message])

    respond_to do |format|
      if @mailee_message.save
        format.html { redirect_to(@mailee_message, :notice => 'Mailee message was successfully created.') }
        format.xml  { render :xml => @mailee_message, :status => :created, :location => @mailee_message }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @mailee_message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /mailee_messages/1
  # PUT /mailee_messages/1.xml
  def update
    @mailee_message = Mailee::Message.find(params[:id])

    respond_to do |format|
      if @mailee_message.update_attributes(params[:mailee_message])
        format.html { redirect_to(@mailee_message, :notice => 'Mailee message was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @mailee_message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /mailee_messages/1
  # DELETE /mailee_messages/1.xml
  def destroy
    @mailee_message = Mailee::Message.find(params[:id])
    @mailee_message.destroy

    respond_to do |format|
      format.html { redirect_to(mailee_messages_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/mailee_messages_helper.rb
module MaileeMessagesHelper
end

app/views/mailee_messages/_form.html.erb
<%= form_for(@mailee_message) do |f| %>
  <% if @mailee_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mailee_message.errors.count, "error") %> prohibited this mailee_message from being saved:</h2>

      <ul>
      <% @mailee_message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :from_name %><br />
    <%= f.text_field :from_name %>
  </div>
  <div class="field">
    <%= f.label :from_email %><br />
    <%= f.text_field :from_email %>
  </div>
  
  <fieldset>
    <legend>Template ou HTML?</legend>
    <div class="field">
      <%= f.label :template_id %><br />
      <%= f.select :template_id, Mailee::Template.all.map{|t| [t.title, t.id]}, {:include_blank => true} %>
    </div>
    <div class="field">
      <%= f.label :html %><br />
      <%= f.text_area :html %>
    </div>
  </fieldset>

  <fieldset>
    <legend>Lista ou contatos?</legend>
    <div class="field">
      <%= f.label :list_id %><br />
      <%= f.select :list_id, Mailee::List.all.map{|t| [t.name, t.id]}, {:include_blank => true}  %>
    </div>
    <div class="field">
      <%= f.label :contacts %><br />
      <%= f.text_area :contacts %>
    </div>
  </fieldset>

  <div class="field">
    <%= f.label :analytics %><br />
    <%= f.check_box :analytics, :value => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mailee_messages/edit.html.erb
<h1>Editing mailee_message</h1>

<%= render 'form' %>

<%= link_to 'Show', @mailee_message %> |
<%= link_to 'Back', mailee_messages_path %>

app/views/mailee_messages/index.html.erb
<h1>Mensagens no Mailee.me</h1>

<table>
  <tr>
    <th>Status</th>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mailee_messages.each do |mailee_message| %>
  <tr>
    <td><%= mailee_message.human_status %></td>
    <td><%= mailee_message.title %></td>
    <td><%= link_to 'Show', mailee_message %></td>
    <td><%= link_to 'Edit', edit_mailee_message_path(mailee_message) %></td>
    <td><%= link_to 'Destroy', mailee_message, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mailee message', new_mailee_message_path %>

app/views/mailee_messages/new.html.erb
<h1>New mailee_message</h1>

<%= render 'form' %>

<%= link_to 'Back', mailee_messages_path %>

app/views/mailee_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @mailee_message.human_status %>
</p>

<% case @mailee_message.status %>
<% when 1 %>
  <form method="post" action="/mailee_messages/<%= @mailee_message.id %>/test">
    <%= token_tag %>
    <input type="text" name="contact_id" />
    <input type="submit" value="Testar" />
  </form>
  <form method="post" action="/mailee_messages/<%= @mailee_message.id %>/ready">
    <%= token_tag %>
    <input type="submit" value="Enviar agora" />
  </form>
  #TODO enviar no futuro
<% when 3 %>
  <%= image_tag @mailee_message.thumb(:large) %>
<% end %>

<p>
  <b>Title:</b>
  <%= @mailee_message.title %>
</p>

<p>
  <b>Subject:</b>
  <%= @mailee_message.subject %>
</p>

<p>
  <b>HTML:</b>
  <%= @mailee_message.html %>
</p>

<p>
  <b>List:</b>
  <%= @mailee_message.list_id %>
</p>

<p>
  <b>From:</b>
  <%= @mailee_message.signature %>
</p>
<p>
  <b>Reply:</b>
  <%= @mailee_message.reply_email %>
</p>

<%= link_to 'Edit', edit_mailee_message_path(@mailee_message) %> |
<%= link_to 'Back', mailee_messages_path %>